# Site settings
title: zyxww
description: "simple blog to collect my thoughts; probably nothing of interest here"
baseurl: ""
url: "http://zyxww.xyz"

excerpt_separator: <!--more-->
paginate: 5

# Default layout for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
markdown: kramdown

# Global settings
timezone: "America/Chicago"

exclude: [resources]

gems:
- jekyll-paginate

